### ISSUE TITLE
gui: improve ESS wording

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#103]
## Tasks

ESS settings menu:

- [ ] rename `Zero feed-in (Fronius PV inverters only)` to `Fronius Zero feed-in`
- [ ] rename `Zero feed-in active` to `Fronius Zero feed-in active`

Fronius PV Inverter menu in the device list:

- [ ] rename `Power limit` to `Zero feed-in power limit`
- [ ] remove `Maximum power` entirely

## Discussion / undecided:

Wording as it is now:

![image](https://cloud.githubusercontent.com/assets/5200296/21104822/47dcb5ae-c088-11e6-9e68-80833cefc1bc.png)

`Minimum Discharge SOC (unless grid fails)`, shorter and still understandable would be `Reserve capacity`.

`Feed-in excess solar charger power`, quite long. But I don't know a better one yet.

Better ideas welcome.

**Comment by mpvader** [comment]
@edevries-victron: please make above mentioned changes. And what is the Maximum power for in the Fronius PV Inverter menu?

![image](https://cloud.githubusercontent.com/assets/5200296/21658278/36fa3f0e-d2c6-11e6-81b6-97e300fcec2f.png)


(in case someone wonders: that %key not found issue% on the website is fixed)

**Comment by edevries-victron** [comment]
@mpvader 'Maximum power' is the maximum (AC) power capability of the inverter itself. This is the maximum AC power the inverter can deliver.

**Comment by edevries-victron** [comment]
After consult with @mpvader: remove 'Maximum power' entry as well.

**Comment by edevries-victron** [comment]
@mpvader 
* 'Reserve battery capacity' seems better to me than 'Reserve capacity', because it gives a hint we're talking about the battery SoC. Otherwise the user may have no clue what it is about.
* I bit nitpicking here: should Zero in Fronius Zero feed-in be capitalized?

**Comment by jhofstee** [comment]
thanks, included in v2.01~7

**Comment by sophiabee005** [comment]
I'm impressed, I have to admit. Seldom do I come across a blog that's both educative and entertaining, and let me tell you, you've hit the nail on the head. The issue is something which not enough folks are speaking intelligently about. I am very happy I found this in my search for something relating to this. 
<a href="https://top5lists.net/todays-the-best-portable-solar-chargers-to-buy/">Best Portable Solar Charger To Buy Now</a>
