### ISSUE TITLE
Vebus: Add BMS Connection lost alarm

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#1032]
Add an on alarm on BOL frame timeouts and VE.Bus BMS frame timeouts. 
See https://www.victronenergy.com/live/mppt-error-codes#err_67_-_bms_connection_lost

Multi firmware >= 502 supports a BOL frames timed out status flag. 

### mk2-dbus:
D-Bus path` /Alarms/BmsConnectionLost` will be added to mk2-dbus

### Todo:

- [x] Add to mk2-dbus
- [x] Add to GUI
- [x] Add to VRM

**Comment by vejpasop** [comment]
Indeed the the low voltage battery will be shown along with the BMS comms lost.
Suppressing this  alarm in vebus-interface is not really favorable (in my opinion) . 
The low battery alarm will usually come up before the comms lost. And after the comms lost it takes a while (>20 seconds) to clear the low voltage alarm, afterwards it will go through a low battery warning. This has to do with the charge engine state in the Multi.

**Comment by vejpasop** [comment]
Correct, 

Only it is note error 67 but a /Alarms/BmsConnectionLost

**Comment by mpvader** [comment]
Can you share me screenshot of how that looks in the gui?

**Comment by vejpasop** [comment]
![image](https://github.com/victronenergy/venus/assets/10847324/5b846a94-c44a-4681-af51-05cba33976ec)

**Comment by warwickchapman** [comment]
Have tested this with site 308284.

### GX
Product | C014
Firmware version | v3.00~42

### VE.Bus
Product | MultiPlus-II 48/5000/70-48
Firmware version | 502

I unplugged the the VE.Bus cable from the GX device to simulate GX failure and after 30 minutes, nothing happened in 30 minutes.

I unplugged the BMS CAN cable from the Cerbo for the BYD BMU and after about 4 mins 30 seconds the BYD BMU shut the batteries down.  The Cerbo reported a low battery and then continued running for an hour with the DC bus energised by the AC Input.  I reconnected the BMS CAN cable and fired the batteries up again:

<img width="495" alt="image" src="https://github.com/victronenergy/venus/assets/6004561/0638644f-426b-4d58-bfdb-22defb2101e6">
<img width="494" alt="image" src="https://github.com/victronenergy/venus/assets/6004561/9779f4d7-5fb9-4ca2-b811-070e53f7e1d4">

I will try this on another system with Freedom Won and report.

**Comment by vejpasop** [comment]
Number 1 can be explained:
The BMS connection lost alarm in case of a managed battery is triggered by the Multi. So the Multi tells the GX device that it did not receive battery management messages for at least 5 minutes,   If you unplug the VE.Bus cable from the Multi the GX device can not read the status and will therefore not show the BMS connection lost.

Number 2 where you disconnect the CAN cable should have triggered a BMS connection lost. 
I will look into that.

**Comment by vejpasop** [comment]
@warwickchapman Found it. I looked on your site. You need to update the MK3 in order for this to work.
