### ISSUE TITLE
vebus: Fix error 11 report for Quattro-II (and MultiGrid)

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#1101]
Compared to the MultiPlus-II The VE.Bus error 11 reason bit definitions are slightly different for the Quattro-II.

Due to a different hardware implementation on the Quattro-II there are no specific relay test steps. So when there is an error it always goes wrong in step1. 

See https://wiki.victronenergy.com/rend/ccgx/specs/mk2-dbus/vebus-error-11

### Implementation details 
CNB software numbers are reported in the version frame remainder. This can be used to determine if we use the BRT method or the current SRT MultiPlus-II relay test.

Bits 3, 2 and 1of eeMultiGridRelayInfo#1 should not be shown in the GUI. These are reserved for debugging purposes only
(These bits could however be usefull for debugging) 

**Note:**  For the MultiGrid the bit meaning is similar to the MP-II. However the test during the steps are different due to a different hardware implementation. So for the MultiGrid the user documentation should be reviewed and adapted accordingly.

### Todo

- [ ] Fix error11 report in GUI
- [ ] mk2-dbus Add item to report relay test method BRT or SRT 
- [ ] Fix info on https://wiki.victronenergy.com/rend/ccgx/specs/mk2-dbus/vebus-error-11 for MultiGrid
- [ ] Fix info https://www.victronenergy.com/live/ve.bus:ve.bus_error_codes#error_11_-_relay_test_fault_-_installation_error_or_possibly_relay_failure
