### ISSUE TITLE
Change settings around VRM / ssh tunnel / remote access

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/venus#1255]
### Current situation

The ssh tunnel for access to local services is started when:

* Remote support is enabled, or
* Remote console (VNC) on VRM is on

The problem is that remote Node-RED and Signal K also needs this tunnel, but there is no 'Node RED on VRM' option. It currently just says in the GUI: "Access node-RED via http://venus.local:1881 and via VRM". But via VRM only works if the ssh tunnel is on, so only when 'remote support' or 'remote console on VRM' is enabled.

### Desired situation

* Probably a new option to 'expose local web services to VRM' should be made. I don't know what the best wording is. It affects both Node-RED and Signal K, but that is probably too long, and may change in the future.
* And, with the GUIv2, the ssh tunnel's run condition for remote console is no longer required, for most people. But, it's still used for when you're running a custom build of the wasm. I'm unsure how to deal with that.

### TODO
VRM logger
- [x] act on VRM Portal == Off, while keeping the ability to log to offline storage.
- [x] log the VRM Portal Setting to VRM when not set to Off. 

venus-html5-app
- help text should be updated, MQTT on LAN (plaintext) will become obsolete (see this [issue](https://github.com/victronenergy/venus-html5-app/issues/433))
- [x] it should connect to nginx, not directly to flashmq, see https://github.com/victronenergy/venus-html5-app/issues/384
- [x] Something must be done about the https -> http redirect in Secure Mode, as is they point to each other. For the time being the https redirect is simply removed.

javascript-vnc-client
- [x] The help text in javascript-vnc-client should be update to mention the new settings: "Make sure to enable Remote
Console for LAN" will be no longer correct. (Jeroen)

gui-v2
- [x] https://github.com/victronenergy/gui-v2/issues/1254 (needs testing)

Others
- [x] Wiebe reported a inconsistent firewall state -> changed to make firewall modifications blocking

Nice to have for later (not blocking v3.50 release):
- [x] Look at node-red if http:// can be made available when the Security Profile is Weak or Unsecured. (prior to v3.50, node-red was only on https, and post v3.50, node-red is also only on https).

done
- [x] The dynamic forwarding rules can disallow VNC access when VRM Portal != FULL. 
- [x] The gui-v1 start script should be updated to the new settings
- [x] Adjust the restore to default functionality accordingly
- [x] Migration path for MQTT should be added
- [x] The login doesn't survive a reboot at the moment

**Comment by mpvader** [comment]
Its taking it a bit wider, but how about we change the Logging to VRM setting (vrmlogger on/off) into a setting with three options. Name of the setting is VRM Portal. Options are:

1. Off
2. Read only. (vrmlogger is enabled)
3. Full access (default)

The VRM two way communication setting, as well as the Remote console on VRM setting can then be removed. What we accomplish then is one setting less.

Resulting settings:

- local gui (gui v1, gui v2)
- remote support (on, off)
- vrm (off, read only, full access)

Services:
- ssh tunnel (starts when remote support is on,

**Comment by mpvader** [comment]
As discussed today, @jhofstee & @jepefe will review the idea and if they agree we go for this.

**Comment by mpvader** [comment]
@martinbosma please take care of the html5 helptext; @mman

**Comment by mpvader** [comment]
@jhofstee , you take care of `The help text in javascript-vnc-client should be update to mention the new settings: "Make sure to enable Remote Console for LAN" will be no longer correct.` ?

Is this text:

![image](https://github.com/user-attachments/assets/b2eb3706-a50d-44fc-a39f-6e25a4596a0d)


My idea for the new text:

Failed to connect. Make sure to enable the Settings -> Remote Console setting, or access [the new Remote UI].`  <- links to `/gui-v2`.

**Comment by jhofstee** [comment]
I made a separate issue for Node-Red, https://github.com/victronenergy/venus/issues/1371, so this can be closed.
