### ISSUE TITLE
venus-docker: enhance it and create various system sets

### ISSUE THREAD

**Issue by mpvader** [victronenergy/venus#380]
### Todo
- [x] Add dbus-spy and dbus-y
- [x] Bind dbus to tcp
- [x] Make a mechanism & add various systems as specced below.
- [x] Document the different systems
- [ ] vrmlogger - depends on [vrm-portal docker issue](https://github.com/victronenergy/vrm-portal/issues/69) See also [here in Slack](https://victrondevelopment.slack.com/archives/CELRUN7J8/p1544099091012000).

https://github.com/victronenergy/venus-docker

### Details
The idea of the docker image is to be able, with a flick of a switch, to choose between different types of systems. The goal is that eases the development of various Venus(-related) components such as html5-app and vrm-portal; but also the gui(-overviews) and systemcalc itself.

When changing from one system type to another, the set of recordings that runs must be changed. And also some settings must be changed.

Systemcalc will normally run; (and of course for development of that, it can be stopped; duh)

For independent things we will make separate start/stop commands:
- tanks
- solar-charger
- AC-coupled PV (on output & input)

To make sure it all makes sense number-wise; issuing such command will also restart the other commands.

To achieve above; the following connections should be up:
- mqtt (already present, both normal & websockified)
- vrmlogger (will be in separate issue)
- dbus (bind it to tcp interface, see [here](https://github.com/sbender9/signalk-venus-plugin#plugin-installation--configuration))

### Systems.

- battery selection should always be on auto; unless specified differently.

**A) Absolut Navetta 68 installation**
- 2 x Skylla-i chargers: grouped as one
  - AC Input current limit & on/off are adjustable.
- One set of paralleled VE.Bus Phoenix Inverter 24/3000 (230V and 120V for USA): in 
  - Only on/off, no AC Input current limit.
- 1 x BMV-700

And there are a few more devices, but they won't be connected to Venus:
- 1 x Phoenix charger 24/25 (for engines)
- 1 x BlueSmart 12/30 IP22 (for generators) Which electrical parameters can be monitored with these machines? (device by device) Is it possible to set alarms or change device functions via the interface with Garmin?"

AC Input 1 & 2 settings are to be configured as not available

![selection_057](https://user-images.githubusercontent.com/851549/50271955-f667ec00-043e-11e9-9826-5d829a9e6d77.png)

**B) Single BMV-700**
Settings:
- Has DC system enabled

html5app: see only battery box & dc loads

**C) Single BMV-702**
BMV configured to measure starter battery voltage.

Settings:
- Has DC-system enabled

html5app: see main battery box & simple battery box with only voltage (the starter battery). And dc loads

**D) Multi + BMV - Off-grid with generator**
VE.Bus:
- CurrentlimitIsAdjustable = false.
- Mode is adjustable = true.

Settings:
- AC input type 1 = Generator
- AC input type 2 = Not available
- has DC system disabled

**E) Multi + BMV - Boat without generator**
VE.Bus:
- CurrentlimitIsAdjustable = true.
- Mode is adjustable = true.

Settings:
- AC input type 1 = Shore
- AC input type 2 = Not available
- has DC system enabled

**F) Quattro + BMV - boat with generator - single phase**
VE.Bus:
- AcIn/0/CurrentlimitIsAdjustable-ac-input = false.
- AcIn/1/CurrentlimitIsAdjustable-ac-input = true.
- Mode is adjustable = true.

Settings:
- AC input type 1 = Generator
- AC input type 2 = Shore
- has DC system enabled

**G) Charger + BMV - simple boat**
Settings:
- AC input type 1 = shore
- AC input type 2 = not available
- has DC system enabled

**H) VE.Direct Inverter + BMV - typical simple vehicle - only charged from alternator**
Settings:
- AC input types both on not available
- has DC system enabled

**I) Quattro without BMV - Hybrid generator - single phase**
VE.Bus:
- AcIn/0/CurrentlimitIsAdjustable-ac-input = false.
- AcIn/1/CurrentlimitIsAdjustable-ac-input = true.
- Mode is adjustable = true.

Settings:
- AC Input type 1 = generator
- AC input type 2 = grid
- has DC system disabled

**J) 4 x BMV-700**
Settings:
- Has DC system enabled

**K) Quattro without BMV - Hybrid generator - three phase**
VE.Bus:
- AcIn/0/CurrentlimitIsAdjustable-ac-input = false.
- AcIn/1/CurrentlimitIsAdjustable-ac-input = true.
- Mode is adjustable = true.

Settings:
- AC Input type 1 = generator
- AC input type 2 = grid
- has DC system disabled

**L) Quattro + BMV - boat with generator - three phase**
VE.Bus:

- AcIn/0/CurrentlimitIsAdjustable-ac-input = false.
- AcIn/1/CurrentlimitIsAdjustable-ac-input = true.
- Mode is adjustable = true.
Settings:

- AC input type 1 = Generator
- AC input type 2 = Shore
- has DC system enabled

**L) Two chargers and to inverters; some huge boat**
VE.Bus:

- proposal to be made by Izak. First fix A though, Navetta.

**Later we'll look into adding ESS etc.**

**Comment by mpvader** [comment]
I’ll close this now. Vrmlogger can be added later; once looking at dockerizing the whole vrm receival-end, backend + frontend
