### ISSUE TITLE
Vebus: Add VE.Bus error code 15 description 

### ISSUE THREAD

**Issue by vejpasop** [victronenergy/venus#869]
VE.Bus error 15 has been defined recently.

**Description**
Error 15 - VE.Bus combination error

VE.Bus products or firmware versions can not be combined

This error can occur for example when an Interface 1140 is combined with a VE.Bus BMS or when the connected VE.Bus product firmware versions are incompatible. The latter can in most cases be solved by updating the firmware.

**Todo**

- [x] Add to mk2-dbus
- [ ] Add to GUI and translations
- [x] Add description to https://www.victronenergy.com/live/ve.bus:ve.bus_error_codes
